apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    app: coworking
  ports:
  - port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking
  template:
    metadata:
      labels:
        app: coworking
    spec:
      containers:
      - name: coworking
        image: <ECR_IMAGE_URI_WILL_BE_ADDED_LATER>
        ports:
        - containerPort: 5153
        envFrom:
        - configMapRef:
            name: coworking-config
        - secretRef:
            name: coworking-secret
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness_check
            port: 5153
          initialDelaySeconds: 5
